@TodoApi_HostAddress = http://localhost:5000

GET {{TodoApi_HostAddress}}/odata/TodoItems
Accept: application/json

###

POST {{TodoApi_HostAddress}}/odata/TodoItems
Content-Type: application/json

{
  "title": "Buy groceries",
  "isComplete": false
}

###

PATCH {{TodoApi_HostAddress}}/odata/TodoItems(1)
Content-Type: application/json

{
  "isComplete": true
}

###

DELETE {{TodoApi_HostAddress}}/odata/TodoItems(1)

###
